# These are the configuration parameters that define the application's behavior
# and which are independent from the underlying technical infrastructure
# See https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

# Basic configuration for the Symfony framework features
framework:
    workflows:
        blog_post:
            type: workflow
            marking_store:
                type: multiple_state
                arguments: [status]
            supports: [AppBundle\Entity\Post]
            places:
                - !php/const:AppBundle\Entity\Post::STATE_DRAFTED
                - !php/const:AppBundle\Entity\Post::STATE_CONTENT_REVIEW_REQUESTED
                - !php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_REVIEW_REQUESTED
                - !php/const:AppBundle\Entity\Post::STATE_CONTENT_CHANGES_REQUESTED
                - !php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_CHANGES_REQUESTED
                - !php/const:AppBundle\Entity\Post::STATE_CONTENT_APPROVED
                - !php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_APPROVED
                - !php/const:AppBundle\Entity\Post::STATE_PUBLISHED
                - !php/const:AppBundle\Entity\Post::STATE_ARCHIVED
            transitions:
                request_review:
                    from: [!php/const:AppBundle\Entity\Post::STATE_DRAFTED]
                    to: [!php/const:AppBundle\Entity\Post::STATE_CONTENT_REVIEW_REQUESTED, !php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_REVIEW_REQUESTED]
                request_content_changes:
                    guard: is_granted('ROLE_ADMIN')
                    from: [!php/const:AppBundle\Entity\Post::STATE_CONTENT_REVIEW_REQUESTED]
                    to: [!php/const:AppBundle\Entity\Post::STATE_CONTENT_CHANGES_REQUESTED]
                apply_content_changes:
                    from: [!php/const:AppBundle\Entity\Post::STATE_CONTENT_CHANGES_REQUESTED]
                    to: [!php/const:AppBundle\Entity\Post::STATE_CONTENT_REVIEW_REQUESTED]
                request_spellcheck_changes:
                    guard: is_granted('ROLE_ADMIN')
                    from: [!php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_REVIEW_REQUESTED]
                    to: [!php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_CHANGES_REQUESTED]
                apply_spellcheck_changes:
                    guard: is_granted('ROLE_ADMIN')
                    from: [!php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_CHANGES_REQUESTED]
                    to: [!php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_REVIEW_REQUESTED]
                accept_content:
                    guard: is_granted('ROLE_ADMIN')
                    from: [!php/const:AppBundle\Entity\Post::STATE_CONTENT_REVIEW_REQUESTED]
                    to: [!php/const:AppBundle\Entity\Post::STATE_CONTENT_APPROVED]
                accept_spellcheck:
                    from: [!php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_REVIEW_REQUESTED]
                    to: [!php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_APPROVED]
                publish:
                    from: [!php/const:AppBundle\Entity\Post::STATE_CONTENT_APPROVED, !php/const:AppBundle\Entity\Post::STATE_SPELLCHECK_APPROVED]
                    to: [!php/const:AppBundle\Entity\Post::STATE_PUBLISHED]
                republish:
                    from: [!php/const:AppBundle\Entity\Post::STATE_ARCHIVED]
                    to: [!php/const:AppBundle\Entity\Post::STATE_PUBLISHED]
                archive:
                    from: [!php/const:AppBundle\Entity\Post::STATE_PUBLISHED]
                    to: [!php/const:AppBundle\Entity\Post::STATE_ARCHIVED]
